INSERT OR IGNORE INTO rooms (id, name, description, n, s, w, e) VALUES
(0, 'Welcome Plaza', 'You stand at the heart of Flavortown, a bustling plaza with a giant neon fork. The air is thick with the stank of programmers.', 1, -1, -1, 2),
(1, 'Flavor Fountain', 'A fountain sprays rainbow colored soda. Locals gather here to chat and sip.', 7, 0, -1, 3),
(2, 'Bent Path', 'The path curves along a canal lined with food stalls. A shipwright stands at east.', -1, -1, 0, 4),
(3, 'Fraud Squad HQ', 'A sleek building with “Fraud Squad” in bold letters. Agents monitor the town’s flavoral integrity.', -1, -1, 1, 5),
(4, 'Shipwrights’ Dock', 'Boats bob in the water. Shipwrights hammer and look after the town.”', 6, -1, 2, 8),
(5, 'Flavor Alley', 'Graffiti of burgers, hot sauce and ASCII characters covers the walls. The alley turns north and east.', 9, -1, 3, 10),
(6, 'Marine Market', 'Vendors sell fresh fish and rare... electronics?.', 11, 4, -1, 7),
(7, 'Living Quarters: West', 'Rows of cozy apartments for Flavortown’s workers.', 12, 1, 6, 13),
(8, 'Shipwrights’ Workshop', 'Sparks fly as shipwrights smash their hammer on the Ruby.', 14, -1, 4, 15),
(9, 'Fraud Squad Barracks', 'Bunks and lockers for the Fraud Squad.”', 16, 5, -1, 17),
(10, 'Flavor Alley East', 'The alley narrows, filled with the aroma of grilled cheese and tasty Chrome extensions.', 18, -1, 5, 19),
(11, 'Merchant’s Row', 'Merchants shout about today’s devlogs. The canal continues north.', 20, 6, -1, 12),
(12, 'Living Quarters: North', 'Dorms for the shipwrights. Laughter echoes.', 21, 7, 11, 22),
(13, 'Chef’s Commons', 'A lounge for chefs to swap suggestions and stories. Almost like #flavortown, whatever that is.', 23, -1, 7, 24),
(14, 'Dry Dock', 'A half-built ship sits on blocks. Tools and blueprints are everywhere. Like an abandoned project. Shame.', 25, 8, -1, 26),
(15, 'Flavortown Ferry', 'A SHIP ready to set sail for the “Isle of Judgement. Where strangers judge your cooking, or so Ive heard.”', 27, -1, 8, -1),
(16, 'Fraud Squad Evidence Room', 'Shelves of confiscated bland ingredients. Is that a secret door?.', 28, 9, -1, 29),
(17, 'Fraud Squad Garage', 'Huge consoles and flavor detecting gadgets cover the walls.', 30, -1, 9, 31),
(18, 'Alley Exit', 'A narrow passage leads to the “Spice Gardens.”', 32, 10, -1, 33),
(19, 'Flavor Alley Dead End', 'A mural of Guy Fieri grins at you. Get it? Flavortown...', 34, -1, 10, -1),
(20, 'Canal Bridge', 'A stone bridge arches over the canal. Ships pass beneath.', 35, 11, -1, 21),
(21, 'Shipwright Lounge', 'Uncomfy chairs and a popcorn machine. The volunteers rest here.', 36, 12, 20, 37),
(22, 'Living Quarters: East', 'More apartments, decorated with festival banners and AI generated advertisements.', 38, -1, 12, 39),
(23, 'Chef’s Storage', 'Shelves of rare spices and javascript frameworks.', 40, 13, -1, 41),
(24, 'Common Kitchen', 'Shipwrights work together to cook one big ship!', 42, -1, 13, 43),
(25, 'Shipwrights’ Lounge', 'Shipwrights relax with mugs of beer', 44, 14, -1, 45),
(26, 'Dry Dock Office', 'Blueprints and database schemas cover the walls.', 46, -1, 14, -1),
(27, 'Isle of Judgement Dock', 'A small island that reeks of judgement looms across the water.', 47, 15, -1, -1),
(28, 'Secret Tunnel', 'A hidden passage beneath the town. It’s chilly and dark.', 48, 16, -1, 49),
(29, 'Fraud Squad Secret Lab', 'Experiments to detect cheaters on Hackatime underway.', 50, -1, 16, -1),
(30, 'Garage Exit', 'A ramp leads up to the racetrack', 51, 17, -1, -1),
(31, 'Gadget Workshop', 'Fraud Squad inventors tinker with sensors.', 52, -1, 17, -1),
(32, 'Spice Gardens', 'Rows of Python libraries and herbs. Bees buzz happily.', 53, 18, -1, -1),
(33, 'Garden Shed', 'Tools and watering cans are stacked neatly.', 54, -1, 18, -1),
(34, 'Secret Room', 'A hidden room with a golden spatula on a pedestal.', 55, 19, -1, -1),
(35, 'Bridge Viewpoint', 'You can see all of Flavortown from here.', -1, 20, -1, -1),
(36, 'Volunteer Storage', 'Boxes of t-shirts and unshipped stickers.', -1, 21, -1, -1),
(37, 'North Plaza', 'A quieter plaza with benches and a view of the canal.', -1, 21, -1, -1),
(38, 'East Market', 'Vendors sell AI tokens and souvenirs.', -1, 22, -1, -1),
(39, 'Banner Alley', 'Colorful banners flutter overhead.', -1, 22, -1, -1),
(40, 'Storage Vault', 'Locked cabinets hold the rarest closed source code.', -1, 23, -1, -1),
(41, 'Recipe Archive', 'Ancient documentation line the shelves. Legacy code, amiright?', -1, 23, -1, -1),
(42, 'Test Kitchen', 'Chefs experiment with wild hot new frameworks.', -1, 24, -1, -1),
(43, 'Common Balcony', 'A balcony overlooks the Welcome Plaza.', -1, 24, -1, -1),
(44, 'Shipwrights’ Trophy Room', 'Trophies for “Best Event Ever” and “Most Flavorful Hull.”', -1, 25, -1, -1),
(45, 'Lounge Balcony', 'A view of the docks and the matrix.', -1, 25, -1, -1),
(46, 'Office Closet', 'A cramped closet with bugfixing equipment.', -1, 26, -1, -1),
(47, 'Isle of Judgement', 'People throwing stars at ships and a mysterious locked gate. Huh.', -1, 27, -1, -1),
(48, 'Tunnel Exit', 'You emerge behind the Fraud Squad HQ.', -1, 28, -1, -1),
(49, 'Tunnel Fork', 'The tunnel splits. One path smells like Rust.', -1, 28, -1, -1),
(50, 'Lab Storage', 'Boxes of flavor samples and unshipped rewards.', -1, 29, -1, -1),
(51, 'Flavor Racetrack', 'A racetrack for Go karts shaped like hot dogs cuz yes.', -1, 30, -1, -1),
(52, 'Workshop Loft', 'A loft above the gadget workshop.', -1, 31, -1, -1),
(53, 'Garden Fountain', 'A small fountain surrounded by flowers.', -1, 32, -1, -1),
(54, 'Shed Attic', 'A dusty attic with old documentation and cookbooks.', -1, 33, -1, -1),
(55, 'Golden Spatula Shrine', 'The legendary spatula glows with power.', -1, 34, -1, -1);
